<a href="https://colab.research.google.com/github/eric-wm-yuen/ml-models/blob/main/Copy_of_keras_test_mnist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# test keras on colab

In [ ]:
# 1 - load datasets mnist
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11501568/11490434 [==============================] - 0s 0us/step


In [ ]:
train_images.shape

(60000, 28, 28)

In [ ]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [ ]:
test_images.shape

(10000, 28, 28)

In [ ]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [ ]:
# define the architecture
from tensorflow import keras
from tensorflow.keras import layers

In [ ]:
model = keras.Sequential([
    layers.Dense(512, activation="relu"),
    layers.Dense(10, activation="softmax")
])

In [ ]:
# compilation step
model.compile(optimizer="rmsprop",
               loss="sparse_categorical_crossentropy",
               metrics=["accuracy"])
    

In [ ]:
# prepare data (normalisation)
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255

In [ ]:
# fit the model

model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 5s 10ms/step - loss: 0.2587 - accuracy: 0.9239
Epoch 2/5
469/469 [==============================] - 5s 10ms/step - loss: 0.1049 - accuracy: 0.9685
Epoch 3/5
469/469 [==============================] - 4s 10ms/step - loss: 0.0686 - accuracy: 0.9794
Epoch 4/5
469/469 [==============================] - 5s 10ms/step - loss: 0.0497 - accuracy: 0.9851
Epoch 5/5
469/469 [==============================] - 5s 10ms/step - loss: 0.0379 - accuracy: 0.9890


In [ ]:
# make predictions based on trained model
test_digits = test_images[0:10]
predictions = model.predict(test_digits)
predictions[0]

array([1.1293554e-09, 1.5912076e-12, 4.2570852e-07, 4.2924203e-06,
       6.5870751e-12, 1.0839614e-08, 2.3042391e-14, 9.9999511e-01,
       5.8586971e-09, 1.2196591e-07], dtype=float32)

In [ ]:
predictions[0].argmax()

7

In [ ]:
test_labels[0]

7

In [ ]:
# Evaluate the model on new data
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"test_acc: {test_acc}")

313/313 [==============================] - 1s 3ms/step - loss: 0.0626 - accuracy: 0.9819
test_acc: 0.9818999767303467
